

# This file was *autogenerated* from the file cp1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5'); _sage_const_100 = Integer(100); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p3 = RealNumber('0.3')# Import necessary libraries
from sage.plot.plot3d.shapes2 import Sphere
from sage.plot.plot3d.all import line3d
import numpy as np

# Create a unit sphere with radius 1
sphere = Sphere(_sage_const_1 )  # Radius of 1

# Create the stereographic projection lines
lines = []
for x in np.linspace(-_sage_const_1 , _sage_const_1 , _sage_const_6 ):  # Example lines
    for y in np.linspace(-_sage_const_1 , _sage_const_1 , _sage_const_6 ):
        if x**_sage_const_2  + y**_sage_const_2  <= _sage_const_1 :
            line = line3d([(_sage_const_0 , _sage_const_0 , _sage_const_1 ), (x, y, _sage_const_0 )], color="black", opacity=_sage_const_0p5 )
            lines.append(line)

# Combine sphere and projection lines
projection = sphere
for l in lines:
    projection += l

# Animate by rotating the projection and saving each frame
angles = np.linspace(_sage_const_0 , _sage_const_2  * np.pi, _sage_const_100 )  # 100 frames
frames = []

for i, angle in enumerate(angles):
    # Rotate the projection around the z-axis by 'angle'
    rotated_projection = projection.rotate([_sage_const_0 , _sage_const_0 , _sage_const_1 ], angle)
    
    # Save each frame as an image
    filename = f"/mnt/data/frame_{i:03d}.png"  # Save the image to a file
    rotated_projection.show(viewer='threejs', figsize=[_sage_const_6 , _sage_const_6 ], frame=False, zoom=_sage_const_1p5 , aspect_ratio=[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ], 
                            color="gray", opacity=_sage_const_0p3 , savefig=filename)
    
    # Keep track of the generated frame filenames
    frames.append(filename)

# Once all frames are generated, you can use them to create an animated GIF or video with external tools
print("All frames have been saved. You can use them to create an animation.")


